#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Common")]
	public partial class DCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblEmployee(tblEmployee instance);
    partial void UpdatetblEmployee(tblEmployee instance);
    partial void DeletetblEmployee(tblEmployee instance);
    partial void InserttblEmployer(tblEmployer instance);
    partial void UpdatetblEmployer(tblEmployer instance);
    partial void DeletetblEmployer(tblEmployer instance);
    partial void InserttblJobOffer(tblJobOffer instance);
    partial void UpdatetblJobOffer(tblJobOffer instance);
    partial void DeletetblJobOffer(tblJobOffer instance);
    partial void InserttblLMIAApplication(tblLMIAApplication instance);
    partial void UpdatetblLMIAApplication(tblLMIAApplication instance);
    partial void DeletetblLMIAApplication(tblLMIAApplication instance);
    #endregion
		
		public DCDataContext() : 
				base(global::Common.Properties.Settings.Default.CommonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblEmployee> tblEmployees
		{
			get
			{
				return this.GetTable<tblEmployee>();
			}
		}
		
		public System.Data.Linq.Table<tblEmployer> tblEmployers
		{
			get
			{
				return this.GetTable<tblEmployer>();
			}
		}
		
		public System.Data.Linq.Table<tblJobOffer> tblJobOffers
		{
			get
			{
				return this.GetTable<tblJobOffer>();
			}
		}
		
		public System.Data.Linq.Table<tblLMIAApplication> tblLMIAApplications
		{
			get
			{
				return this.GetTable<tblLMIAApplication>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmployee")]
	public partial class tblEmployee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _PersonId;
		
		private string _OutCanadaCity;
		
		private string _OutCanadaCountry;
		
		private string _StatusinCanada;
		
		private string _CanadaCity;
		
		private string _CanadaProvince;
		
		private System.Nullable<int> _Visitor;
		
		private System.Nullable<int> _Student;
		
		private System.Nullable<int> _ForeignWorker;
		
		private System.Nullable<int> _RefugeeClaimant;
		
		private System.Nullable<int> _Hired;
		
		private string _Duration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPersonIdChanging(System.Nullable<int> value);
    partial void OnPersonIdChanged();
    partial void OnOutCanadaCityChanging(string value);
    partial void OnOutCanadaCityChanged();
    partial void OnOutCanadaCountryChanging(string value);
    partial void OnOutCanadaCountryChanged();
    partial void OnStatusinCanadaChanging(string value);
    partial void OnStatusinCanadaChanged();
    partial void OnCanadaCityChanging(string value);
    partial void OnCanadaCityChanged();
    partial void OnCanadaProvinceChanging(string value);
    partial void OnCanadaProvinceChanged();
    partial void OnVisitorChanging(System.Nullable<int> value);
    partial void OnVisitorChanged();
    partial void OnStudentChanging(System.Nullable<int> value);
    partial void OnStudentChanged();
    partial void OnForeignWorkerChanging(System.Nullable<int> value);
    partial void OnForeignWorkerChanged();
    partial void OnRefugeeClaimantChanging(System.Nullable<int> value);
    partial void OnRefugeeClaimantChanged();
    partial void OnHiredChanging(System.Nullable<int> value);
    partial void OnHiredChanged();
    partial void OnDurationChanging(string value);
    partial void OnDurationChanged();
    #endregion
		
		public tblEmployee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonId", DbType="Int")]
		public System.Nullable<int> PersonId
		{
			get
			{
				return this._PersonId;
			}
			set
			{
				if ((this._PersonId != value))
				{
					this.OnPersonIdChanging(value);
					this.SendPropertyChanging();
					this._PersonId = value;
					this.SendPropertyChanged("PersonId");
					this.OnPersonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutCanadaCity", DbType="NVarChar(20)")]
		public string OutCanadaCity
		{
			get
			{
				return this._OutCanadaCity;
			}
			set
			{
				if ((this._OutCanadaCity != value))
				{
					this.OnOutCanadaCityChanging(value);
					this.SendPropertyChanging();
					this._OutCanadaCity = value;
					this.SendPropertyChanged("OutCanadaCity");
					this.OnOutCanadaCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutCanadaCountry", DbType="NVarChar(20)")]
		public string OutCanadaCountry
		{
			get
			{
				return this._OutCanadaCountry;
			}
			set
			{
				if ((this._OutCanadaCountry != value))
				{
					this.OnOutCanadaCountryChanging(value);
					this.SendPropertyChanging();
					this._OutCanadaCountry = value;
					this.SendPropertyChanged("OutCanadaCountry");
					this.OnOutCanadaCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusinCanada", DbType="NVarChar(20)")]
		public string StatusinCanada
		{
			get
			{
				return this._StatusinCanada;
			}
			set
			{
				if ((this._StatusinCanada != value))
				{
					this.OnStatusinCanadaChanging(value);
					this.SendPropertyChanging();
					this._StatusinCanada = value;
					this.SendPropertyChanged("StatusinCanada");
					this.OnStatusinCanadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanadaCity", DbType="NVarChar(20)")]
		public string CanadaCity
		{
			get
			{
				return this._CanadaCity;
			}
			set
			{
				if ((this._CanadaCity != value))
				{
					this.OnCanadaCityChanging(value);
					this.SendPropertyChanging();
					this._CanadaCity = value;
					this.SendPropertyChanged("CanadaCity");
					this.OnCanadaCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanadaProvince", DbType="NVarChar(20)")]
		public string CanadaProvince
		{
			get
			{
				return this._CanadaProvince;
			}
			set
			{
				if ((this._CanadaProvince != value))
				{
					this.OnCanadaProvinceChanging(value);
					this.SendPropertyChanging();
					this._CanadaProvince = value;
					this.SendPropertyChanged("CanadaProvince");
					this.OnCanadaProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visitor", DbType="Int")]
		public System.Nullable<int> Visitor
		{
			get
			{
				return this._Visitor;
			}
			set
			{
				if ((this._Visitor != value))
				{
					this.OnVisitorChanging(value);
					this.SendPropertyChanging();
					this._Visitor = value;
					this.SendPropertyChanged("Visitor");
					this.OnVisitorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student", DbType="Int")]
		public System.Nullable<int> Student
		{
			get
			{
				return this._Student;
			}
			set
			{
				if ((this._Student != value))
				{
					this.OnStudentChanging(value);
					this.SendPropertyChanging();
					this._Student = value;
					this.SendPropertyChanged("Student");
					this.OnStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForeignWorker", DbType="Int")]
		public System.Nullable<int> ForeignWorker
		{
			get
			{
				return this._ForeignWorker;
			}
			set
			{
				if ((this._ForeignWorker != value))
				{
					this.OnForeignWorkerChanging(value);
					this.SendPropertyChanging();
					this._ForeignWorker = value;
					this.SendPropertyChanged("ForeignWorker");
					this.OnForeignWorkerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefugeeClaimant", DbType="Int")]
		public System.Nullable<int> RefugeeClaimant
		{
			get
			{
				return this._RefugeeClaimant;
			}
			set
			{
				if ((this._RefugeeClaimant != value))
				{
					this.OnRefugeeClaimantChanging(value);
					this.SendPropertyChanging();
					this._RefugeeClaimant = value;
					this.SendPropertyChanged("RefugeeClaimant");
					this.OnRefugeeClaimantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hired", DbType="Int")]
		public System.Nullable<int> Hired
		{
			get
			{
				return this._Hired;
			}
			set
			{
				if ((this._Hired != value))
				{
					this.OnHiredChanging(value);
					this.SendPropertyChanging();
					this._Hired = value;
					this.SendPropertyChanged("Hired");
					this.OnHiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="NVarChar(30)")]
		public string Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this.OnDurationChanging(value);
					this.SendPropertyChanging();
					this._Duration = value;
					this.SendPropertyChanged("Duration");
					this.OnDurationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmployer")]
	public partial class tblEmployer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ESDCId;
		
		private string _CRA_BN;
		
		private string _LegalName;
		
		private string _OperatingName;
		
		private string _FranchiseName;
		
		private System.Nullable<int> _FranchiseAware;
		
		private System.Nullable<int> _CompanyType;
		
		private System.Nullable<int> _MailAddressId;
		
		private System.Nullable<int> _BizAddressId;
		
		private string _BizTelephone;
		
		private string _Website;
		
		private System.Nullable<System.DateTime> _BizStartDate;
		
		private string _BizActivity;
		
		private string _ContactFirstName;
		
		private string _ContactMiddleName;
		
		private string _ContactLastName;
		
		private string _ContactJobTitle;
		
		private string _ContactPhone;
		
		private string _ContactFax;
		
		private string _ContactEmail;
		
		private string _theWitness;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnESDCIdChanging(string value);
    partial void OnESDCIdChanged();
    partial void OnCRA_BNChanging(string value);
    partial void OnCRA_BNChanged();
    partial void OnLegalNameChanging(string value);
    partial void OnLegalNameChanged();
    partial void OnOperatingNameChanging(string value);
    partial void OnOperatingNameChanged();
    partial void OnFranchiseNameChanging(string value);
    partial void OnFranchiseNameChanged();
    partial void OnFranchiseAwareChanging(System.Nullable<int> value);
    partial void OnFranchiseAwareChanged();
    partial void OnCompanyTypeChanging(System.Nullable<int> value);
    partial void OnCompanyTypeChanged();
    partial void OnMailAddressIdChanging(System.Nullable<int> value);
    partial void OnMailAddressIdChanged();
    partial void OnBizAddressIdChanging(System.Nullable<int> value);
    partial void OnBizAddressIdChanged();
    partial void OnBizTelephoneChanging(string value);
    partial void OnBizTelephoneChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnBizStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBizStartDateChanged();
    partial void OnBizActivityChanging(string value);
    partial void OnBizActivityChanged();
    partial void OnContactFirstNameChanging(string value);
    partial void OnContactFirstNameChanged();
    partial void OnContactMiddleNameChanging(string value);
    partial void OnContactMiddleNameChanged();
    partial void OnContactLastNameChanging(string value);
    partial void OnContactLastNameChanged();
    partial void OnContactJobTitleChanging(string value);
    partial void OnContactJobTitleChanged();
    partial void OnContactPhoneChanging(string value);
    partial void OnContactPhoneChanged();
    partial void OnContactFaxChanging(string value);
    partial void OnContactFaxChanged();
    partial void OnContactEmailChanging(string value);
    partial void OnContactEmailChanged();
    partial void OntheWitnessChanging(string value);
    partial void OntheWitnessChanged();
    #endregion
		
		public tblEmployer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESDCId", DbType="Char(6)")]
		public string ESDCId
		{
			get
			{
				return this._ESDCId;
			}
			set
			{
				if ((this._ESDCId != value))
				{
					this.OnESDCIdChanging(value);
					this.SendPropertyChanging();
					this._ESDCId = value;
					this.SendPropertyChanged("ESDCId");
					this.OnESDCIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRA_BN", DbType="NVarChar(15)")]
		public string CRA_BN
		{
			get
			{
				return this._CRA_BN;
			}
			set
			{
				if ((this._CRA_BN != value))
				{
					this.OnCRA_BNChanging(value);
					this.SendPropertyChanging();
					this._CRA_BN = value;
					this.SendPropertyChanged("CRA_BN");
					this.OnCRA_BNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegalName", DbType="NVarChar(50)")]
		public string LegalName
		{
			get
			{
				return this._LegalName;
			}
			set
			{
				if ((this._LegalName != value))
				{
					this.OnLegalNameChanging(value);
					this.SendPropertyChanging();
					this._LegalName = value;
					this.SendPropertyChanged("LegalName");
					this.OnLegalNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatingName", DbType="NVarChar(50)")]
		public string OperatingName
		{
			get
			{
				return this._OperatingName;
			}
			set
			{
				if ((this._OperatingName != value))
				{
					this.OnOperatingNameChanging(value);
					this.SendPropertyChanging();
					this._OperatingName = value;
					this.SendPropertyChanged("OperatingName");
					this.OnOperatingNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FranchiseName", DbType="NVarChar(50)")]
		public string FranchiseName
		{
			get
			{
				return this._FranchiseName;
			}
			set
			{
				if ((this._FranchiseName != value))
				{
					this.OnFranchiseNameChanging(value);
					this.SendPropertyChanging();
					this._FranchiseName = value;
					this.SendPropertyChanged("FranchiseName");
					this.OnFranchiseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FranchiseAware", DbType="Int")]
		public System.Nullable<int> FranchiseAware
		{
			get
			{
				return this._FranchiseAware;
			}
			set
			{
				if ((this._FranchiseAware != value))
				{
					this.OnFranchiseAwareChanging(value);
					this.SendPropertyChanging();
					this._FranchiseAware = value;
					this.SendPropertyChanged("FranchiseAware");
					this.OnFranchiseAwareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyType", DbType="Int")]
		public System.Nullable<int> CompanyType
		{
			get
			{
				return this._CompanyType;
			}
			set
			{
				if ((this._CompanyType != value))
				{
					this.OnCompanyTypeChanging(value);
					this.SendPropertyChanging();
					this._CompanyType = value;
					this.SendPropertyChanged("CompanyType");
					this.OnCompanyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailAddressId", DbType="Int")]
		public System.Nullable<int> MailAddressId
		{
			get
			{
				return this._MailAddressId;
			}
			set
			{
				if ((this._MailAddressId != value))
				{
					this.OnMailAddressIdChanging(value);
					this.SendPropertyChanging();
					this._MailAddressId = value;
					this.SendPropertyChanged("MailAddressId");
					this.OnMailAddressIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BizAddressId", DbType="Int")]
		public System.Nullable<int> BizAddressId
		{
			get
			{
				return this._BizAddressId;
			}
			set
			{
				if ((this._BizAddressId != value))
				{
					this.OnBizAddressIdChanging(value);
					this.SendPropertyChanging();
					this._BizAddressId = value;
					this.SendPropertyChanged("BizAddressId");
					this.OnBizAddressIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BizTelephone", DbType="NVarChar(20)")]
		public string BizTelephone
		{
			get
			{
				return this._BizTelephone;
			}
			set
			{
				if ((this._BizTelephone != value))
				{
					this.OnBizTelephoneChanging(value);
					this.SendPropertyChanging();
					this._BizTelephone = value;
					this.SendPropertyChanged("BizTelephone");
					this.OnBizTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(100)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BizStartDate", DbType="Date")]
		public System.Nullable<System.DateTime> BizStartDate
		{
			get
			{
				return this._BizStartDate;
			}
			set
			{
				if ((this._BizStartDate != value))
				{
					this.OnBizStartDateChanging(value);
					this.SendPropertyChanging();
					this._BizStartDate = value;
					this.SendPropertyChanged("BizStartDate");
					this.OnBizStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BizActivity", DbType="NVarChar(100)")]
		public string BizActivity
		{
			get
			{
				return this._BizActivity;
			}
			set
			{
				if ((this._BizActivity != value))
				{
					this.OnBizActivityChanging(value);
					this.SendPropertyChanging();
					this._BizActivity = value;
					this.SendPropertyChanged("BizActivity");
					this.OnBizActivityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactFirstName", DbType="NVarChar(20)")]
		public string ContactFirstName
		{
			get
			{
				return this._ContactFirstName;
			}
			set
			{
				if ((this._ContactFirstName != value))
				{
					this.OnContactFirstNameChanging(value);
					this.SendPropertyChanging();
					this._ContactFirstName = value;
					this.SendPropertyChanged("ContactFirstName");
					this.OnContactFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactMiddleName", DbType="NVarChar(20)")]
		public string ContactMiddleName
		{
			get
			{
				return this._ContactMiddleName;
			}
			set
			{
				if ((this._ContactMiddleName != value))
				{
					this.OnContactMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._ContactMiddleName = value;
					this.SendPropertyChanged("ContactMiddleName");
					this.OnContactMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactLastName", DbType="NVarChar(20)")]
		public string ContactLastName
		{
			get
			{
				return this._ContactLastName;
			}
			set
			{
				if ((this._ContactLastName != value))
				{
					this.OnContactLastNameChanging(value);
					this.SendPropertyChanging();
					this._ContactLastName = value;
					this.SendPropertyChanged("ContactLastName");
					this.OnContactLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactJobTitle", DbType="NVarChar(20)")]
		public string ContactJobTitle
		{
			get
			{
				return this._ContactJobTitle;
			}
			set
			{
				if ((this._ContactJobTitle != value))
				{
					this.OnContactJobTitleChanging(value);
					this.SendPropertyChanging();
					this._ContactJobTitle = value;
					this.SendPropertyChanged("ContactJobTitle");
					this.OnContactJobTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPhone", DbType="NVarChar(20)")]
		public string ContactPhone
		{
			get
			{
				return this._ContactPhone;
			}
			set
			{
				if ((this._ContactPhone != value))
				{
					this.OnContactPhoneChanging(value);
					this.SendPropertyChanging();
					this._ContactPhone = value;
					this.SendPropertyChanged("ContactPhone");
					this.OnContactPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactFax", DbType="NVarChar(20)")]
		public string ContactFax
		{
			get
			{
				return this._ContactFax;
			}
			set
			{
				if ((this._ContactFax != value))
				{
					this.OnContactFaxChanging(value);
					this.SendPropertyChanging();
					this._ContactFax = value;
					this.SendPropertyChanged("ContactFax");
					this.OnContactFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="NVarChar(50)")]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this.OnContactEmailChanging(value);
					this.SendPropertyChanging();
					this._ContactEmail = value;
					this.SendPropertyChanged("ContactEmail");
					this.OnContactEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theWitness", DbType="NVarChar(20)")]
		public string theWitness
		{
			get
			{
				return this._theWitness;
			}
			set
			{
				if ((this._theWitness != value))
				{
					this.OntheWitnessChanging(value);
					this.SendPropertyChanging();
					this._theWitness = value;
					this.SendPropertyChanged("theWitness");
					this.OntheWitnessChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblJobOffer")]
	public partial class tblJobOffer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _applicationID;
		
		private string _jobTile;
		
		private System.Nullable<int> _numOfTFWs;
		
		private System.Nullable<int> _duration;
		
		private System.Nullable<int> _durationUnit;
		
		private string _durationRationale;
		
		private System.Nullable<System.DateTime> _startDate;
		
		private System.Nullable<bool> _languageRequired;
		
		private System.Nullable<bool> _readingEnglishFrenchRequied;
		
		private System.Nullable<bool> _readingEnglishRequired;
		
		private System.Nullable<bool> _readingFrenchRequired;
		
		private System.Nullable<bool> _readingEnglishOrFrenchRequired;
		
		private System.Nullable<bool> _readingEnglishAndFrenchRequired;
		
		private System.Nullable<bool> _writingEnglishFrenchRequired;
		
		private System.Nullable<bool> _writingEnglishRequired;
		
		private System.Nullable<bool> _writingFrenchRequired;
		
		private System.Nullable<bool> _writingEnglishOrFrenchRequired;
		
		private System.Nullable<bool> _writingEnglishAndFrenchRequired;
		
		private System.Nullable<bool> _otherLanguageRequired;
		
		private string _otherLanguageExplanation;
		
		private System.Nullable<int> _vacationDays;
		
		private System.Nullable<int> _remuneration;
		
		private string _otherBenefit;
		
		private System.Nullable<bool> _isSeasonal;
		
		private System.Nullable<bool> _isFullyCoveredLMIA;
		
		private string _notFullyCoveredReason;
		
		private System.Nullable<bool> _isJobLicensed;
		
		private string _licenseAuthority;
		
		private System.Nullable<bool> _licenseReady;
		
		private System.Nullable<int> _licenseReadyTime;
		
		private string _licenseReadyUnit;
		
		private System.Nullable<bool> _isJobUnion;
		
		private string _unionNameLocation;
		
		private System.Nullable<bool> _isUnionConsulted;
		
		private string _unionNotExplanation;
		
		private string _unionOpinion;
		
		private System.Nullable<bool> _attemptedRecruitCanadian;
		
		private string _notAttemptedReason;
		
		private string _OfficialAdNumber;
		
		private string _briefBenefit;
		
		private string _detailedBenefit;
		
		private string _briefRationaleOfferingJob;
		
		private string _detailedRationaleOfferingJob;
		
		private System.Nullable<bool> _trainCanadian;
		
		private string _noTrainReason;
		
		private string _trainPlanBrief;
		
		private string _trainPlanDetails;
		
		private System.Nullable<bool> _willProvideAccomadation;
		
		private string _notProvideButOffer;
		
		private System.Nullable<int> _provideRent;
		
		private string _provideUnit;
		
		private string _accommodationDescription;
		
		private System.Nullable<bool> _accomadationNotApplicalbe;
		
		private string _whoIsFillingBrief;
		
		private string _whoIsFillingDetail;
		
		private string _howDidYouFindBrief;
		
		private string _howDidYouFindDetail;
		
		private string _howDidYouDetermineBrief;
		
		private string _howDidYouDetermineDetail;
		
		private string _howAndWhenOfferBrief;
		
		private string _howAndWhenOfferDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnapplicationIDChanging(System.Nullable<int> value);
    partial void OnapplicationIDChanged();
    partial void OnjobTileChanging(string value);
    partial void OnjobTileChanged();
    partial void OnnumOfTFWsChanging(System.Nullable<int> value);
    partial void OnnumOfTFWsChanged();
    partial void OndurationChanging(System.Nullable<int> value);
    partial void OndurationChanged();
    partial void OndurationUnitChanging(System.Nullable<int> value);
    partial void OndurationUnitChanged();
    partial void OndurationRationaleChanging(string value);
    partial void OndurationRationaleChanged();
    partial void OnstartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnstartDateChanged();
    partial void OnlanguageRequiredChanging(System.Nullable<bool> value);
    partial void OnlanguageRequiredChanged();
    partial void OnreadingEnglishFrenchRequiedChanging(System.Nullable<bool> value);
    partial void OnreadingEnglishFrenchRequiedChanged();
    partial void OnreadingEnglishRequiredChanging(System.Nullable<bool> value);
    partial void OnreadingEnglishRequiredChanged();
    partial void OnreadingFrenchRequiredChanging(System.Nullable<bool> value);
    partial void OnreadingFrenchRequiredChanged();
    partial void OnreadingEnglishOrFrenchRequiredChanging(System.Nullable<bool> value);
    partial void OnreadingEnglishOrFrenchRequiredChanged();
    partial void OnreadingEnglishAndFrenchRequiredChanging(System.Nullable<bool> value);
    partial void OnreadingEnglishAndFrenchRequiredChanged();
    partial void OnwritingEnglishFrenchRequiredChanging(System.Nullable<bool> value);
    partial void OnwritingEnglishFrenchRequiredChanged();
    partial void OnwritingEnglishRequiredChanging(System.Nullable<bool> value);
    partial void OnwritingEnglishRequiredChanged();
    partial void OnwritingFrenchRequiredChanging(System.Nullable<bool> value);
    partial void OnwritingFrenchRequiredChanged();
    partial void OnwritingEnglishOrFrenchRequiredChanging(System.Nullable<bool> value);
    partial void OnwritingEnglishOrFrenchRequiredChanged();
    partial void OnwritingEnglishAndFrenchRequiredChanging(System.Nullable<bool> value);
    partial void OnwritingEnglishAndFrenchRequiredChanged();
    partial void OnotherLanguageRequiredChanging(System.Nullable<bool> value);
    partial void OnotherLanguageRequiredChanged();
    partial void OnotherLanguageExplanationChanging(string value);
    partial void OnotherLanguageExplanationChanged();
    partial void OnvacationDaysChanging(System.Nullable<int> value);
    partial void OnvacationDaysChanged();
    partial void OnremunerationChanging(System.Nullable<int> value);
    partial void OnremunerationChanged();
    partial void OnotherBenefitChanging(string value);
    partial void OnotherBenefitChanged();
    partial void OnisSeasonalChanging(System.Nullable<bool> value);
    partial void OnisSeasonalChanged();
    partial void OnisFullyCoveredLMIAChanging(System.Nullable<bool> value);
    partial void OnisFullyCoveredLMIAChanged();
    partial void OnnotFullyCoveredReasonChanging(string value);
    partial void OnnotFullyCoveredReasonChanged();
    partial void OnisJobLicensedChanging(System.Nullable<bool> value);
    partial void OnisJobLicensedChanged();
    partial void OnlicenseAuthorityChanging(string value);
    partial void OnlicenseAuthorityChanged();
    partial void OnlicenseReadyChanging(System.Nullable<bool> value);
    partial void OnlicenseReadyChanged();
    partial void OnlicenseReadyTimeChanging(System.Nullable<int> value);
    partial void OnlicenseReadyTimeChanged();
    partial void OnlicenseReadyUnitChanging(string value);
    partial void OnlicenseReadyUnitChanged();
    partial void OnisJobUnionChanging(System.Nullable<bool> value);
    partial void OnisJobUnionChanged();
    partial void OnunionNameLocationChanging(string value);
    partial void OnunionNameLocationChanged();
    partial void OnisUnionConsultedChanging(System.Nullable<bool> value);
    partial void OnisUnionConsultedChanged();
    partial void OnunionNotExplanationChanging(string value);
    partial void OnunionNotExplanationChanged();
    partial void OnunionOpinionChanging(string value);
    partial void OnunionOpinionChanged();
    partial void OnattemptedRecruitCanadianChanging(System.Nullable<bool> value);
    partial void OnattemptedRecruitCanadianChanged();
    partial void OnnotAttemptedReasonChanging(string value);
    partial void OnnotAttemptedReasonChanged();
    partial void OnOfficialAdNumberChanging(string value);
    partial void OnOfficialAdNumberChanged();
    partial void OnbriefBenefitChanging(string value);
    partial void OnbriefBenefitChanged();
    partial void OndetailedBenefitChanging(string value);
    partial void OndetailedBenefitChanged();
    partial void OnbriefRationaleOfferingJobChanging(string value);
    partial void OnbriefRationaleOfferingJobChanged();
    partial void OndetailedRationaleOfferingJobChanging(string value);
    partial void OndetailedRationaleOfferingJobChanged();
    partial void OntrainCanadianChanging(System.Nullable<bool> value);
    partial void OntrainCanadianChanged();
    partial void OnnoTrainReasonChanging(string value);
    partial void OnnoTrainReasonChanged();
    partial void OntrainPlanBriefChanging(string value);
    partial void OntrainPlanBriefChanged();
    partial void OntrainPlanDetailsChanging(string value);
    partial void OntrainPlanDetailsChanged();
    partial void OnwillProvideAccomadationChanging(System.Nullable<bool> value);
    partial void OnwillProvideAccomadationChanged();
    partial void OnnotProvideButOfferChanging(string value);
    partial void OnnotProvideButOfferChanged();
    partial void OnprovideRentChanging(System.Nullable<int> value);
    partial void OnprovideRentChanged();
    partial void OnprovideUnitChanging(string value);
    partial void OnprovideUnitChanged();
    partial void OnaccommodationDescriptionChanging(string value);
    partial void OnaccommodationDescriptionChanged();
    partial void OnaccomadationNotApplicalbeChanging(System.Nullable<bool> value);
    partial void OnaccomadationNotApplicalbeChanged();
    partial void OnwhoIsFillingBriefChanging(string value);
    partial void OnwhoIsFillingBriefChanged();
    partial void OnwhoIsFillingDetailChanging(string value);
    partial void OnwhoIsFillingDetailChanged();
    partial void OnhowDidYouFindBriefChanging(string value);
    partial void OnhowDidYouFindBriefChanged();
    partial void OnhowDidYouFindDetailChanging(string value);
    partial void OnhowDidYouFindDetailChanged();
    partial void OnhowDidYouDetermineBriefChanging(string value);
    partial void OnhowDidYouDetermineBriefChanged();
    partial void OnhowDidYouDetermineDetailChanging(string value);
    partial void OnhowDidYouDetermineDetailChanged();
    partial void OnhowAndWhenOfferBriefChanging(string value);
    partial void OnhowAndWhenOfferBriefChanged();
    partial void OnhowAndWhenOfferDetailChanging(string value);
    partial void OnhowAndWhenOfferDetailChanged();
    #endregion
		
		public tblJobOffer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applicationID", DbType="Int")]
		public System.Nullable<int> applicationID
		{
			get
			{
				return this._applicationID;
			}
			set
			{
				if ((this._applicationID != value))
				{
					this.OnapplicationIDChanging(value);
					this.SendPropertyChanging();
					this._applicationID = value;
					this.SendPropertyChanged("applicationID");
					this.OnapplicationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobTile", DbType="VarChar(30)")]
		public string jobTile
		{
			get
			{
				return this._jobTile;
			}
			set
			{
				if ((this._jobTile != value))
				{
					this.OnjobTileChanging(value);
					this.SendPropertyChanging();
					this._jobTile = value;
					this.SendPropertyChanged("jobTile");
					this.OnjobTileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOfTFWs", DbType="Int")]
		public System.Nullable<int> numOfTFWs
		{
			get
			{
				return this._numOfTFWs;
			}
			set
			{
				if ((this._numOfTFWs != value))
				{
					this.OnnumOfTFWsChanging(value);
					this.SendPropertyChanging();
					this._numOfTFWs = value;
					this.SendPropertyChanged("numOfTFWs");
					this.OnnumOfTFWsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="Int")]
		public System.Nullable<int> duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durationUnit", DbType="Int")]
		public System.Nullable<int> durationUnit
		{
			get
			{
				return this._durationUnit;
			}
			set
			{
				if ((this._durationUnit != value))
				{
					this.OndurationUnitChanging(value);
					this.SendPropertyChanging();
					this._durationUnit = value;
					this.SendPropertyChanged("durationUnit");
					this.OndurationUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durationRationale", DbType="VarChar(150)")]
		public string durationRationale
		{
			get
			{
				return this._durationRationale;
			}
			set
			{
				if ((this._durationRationale != value))
				{
					this.OndurationRationaleChanging(value);
					this.SendPropertyChanging();
					this._durationRationale = value;
					this.SendPropertyChanged("durationRationale");
					this.OndurationRationaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="Date")]
		public System.Nullable<System.DateTime> startDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				if ((this._startDate != value))
				{
					this.OnstartDateChanging(value);
					this.SendPropertyChanging();
					this._startDate = value;
					this.SendPropertyChanged("startDate");
					this.OnstartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_languageRequired", DbType="Bit")]
		public System.Nullable<bool> languageRequired
		{
			get
			{
				return this._languageRequired;
			}
			set
			{
				if ((this._languageRequired != value))
				{
					this.OnlanguageRequiredChanging(value);
					this.SendPropertyChanging();
					this._languageRequired = value;
					this.SendPropertyChanged("languageRequired");
					this.OnlanguageRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readingEnglishFrenchRequied", DbType="Bit")]
		public System.Nullable<bool> readingEnglishFrenchRequied
		{
			get
			{
				return this._readingEnglishFrenchRequied;
			}
			set
			{
				if ((this._readingEnglishFrenchRequied != value))
				{
					this.OnreadingEnglishFrenchRequiedChanging(value);
					this.SendPropertyChanging();
					this._readingEnglishFrenchRequied = value;
					this.SendPropertyChanged("readingEnglishFrenchRequied");
					this.OnreadingEnglishFrenchRequiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readingEnglishRequired", DbType="Bit")]
		public System.Nullable<bool> readingEnglishRequired
		{
			get
			{
				return this._readingEnglishRequired;
			}
			set
			{
				if ((this._readingEnglishRequired != value))
				{
					this.OnreadingEnglishRequiredChanging(value);
					this.SendPropertyChanging();
					this._readingEnglishRequired = value;
					this.SendPropertyChanged("readingEnglishRequired");
					this.OnreadingEnglishRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readingFrenchRequired", DbType="Bit")]
		public System.Nullable<bool> readingFrenchRequired
		{
			get
			{
				return this._readingFrenchRequired;
			}
			set
			{
				if ((this._readingFrenchRequired != value))
				{
					this.OnreadingFrenchRequiredChanging(value);
					this.SendPropertyChanging();
					this._readingFrenchRequired = value;
					this.SendPropertyChanged("readingFrenchRequired");
					this.OnreadingFrenchRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readingEnglishOrFrenchRequired", DbType="Bit")]
		public System.Nullable<bool> readingEnglishOrFrenchRequired
		{
			get
			{
				return this._readingEnglishOrFrenchRequired;
			}
			set
			{
				if ((this._readingEnglishOrFrenchRequired != value))
				{
					this.OnreadingEnglishOrFrenchRequiredChanging(value);
					this.SendPropertyChanging();
					this._readingEnglishOrFrenchRequired = value;
					this.SendPropertyChanged("readingEnglishOrFrenchRequired");
					this.OnreadingEnglishOrFrenchRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_readingEnglishAndFrenchRequired", DbType="Bit")]
		public System.Nullable<bool> readingEnglishAndFrenchRequired
		{
			get
			{
				return this._readingEnglishAndFrenchRequired;
			}
			set
			{
				if ((this._readingEnglishAndFrenchRequired != value))
				{
					this.OnreadingEnglishAndFrenchRequiredChanging(value);
					this.SendPropertyChanging();
					this._readingEnglishAndFrenchRequired = value;
					this.SendPropertyChanged("readingEnglishAndFrenchRequired");
					this.OnreadingEnglishAndFrenchRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_writingEnglishFrenchRequired", DbType="Bit")]
		public System.Nullable<bool> writingEnglishFrenchRequired
		{
			get
			{
				return this._writingEnglishFrenchRequired;
			}
			set
			{
				if ((this._writingEnglishFrenchRequired != value))
				{
					this.OnwritingEnglishFrenchRequiredChanging(value);
					this.SendPropertyChanging();
					this._writingEnglishFrenchRequired = value;
					this.SendPropertyChanged("writingEnglishFrenchRequired");
					this.OnwritingEnglishFrenchRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_writingEnglishRequired", DbType="Bit")]
		public System.Nullable<bool> writingEnglishRequired
		{
			get
			{
				return this._writingEnglishRequired;
			}
			set
			{
				if ((this._writingEnglishRequired != value))
				{
					this.OnwritingEnglishRequiredChanging(value);
					this.SendPropertyChanging();
					this._writingEnglishRequired = value;
					this.SendPropertyChanged("writingEnglishRequired");
					this.OnwritingEnglishRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_writingFrenchRequired", DbType="Bit")]
		public System.Nullable<bool> writingFrenchRequired
		{
			get
			{
				return this._writingFrenchRequired;
			}
			set
			{
				if ((this._writingFrenchRequired != value))
				{
					this.OnwritingFrenchRequiredChanging(value);
					this.SendPropertyChanging();
					this._writingFrenchRequired = value;
					this.SendPropertyChanged("writingFrenchRequired");
					this.OnwritingFrenchRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_writingEnglishOrFrenchRequired", DbType="Bit")]
		public System.Nullable<bool> writingEnglishOrFrenchRequired
		{
			get
			{
				return this._writingEnglishOrFrenchRequired;
			}
			set
			{
				if ((this._writingEnglishOrFrenchRequired != value))
				{
					this.OnwritingEnglishOrFrenchRequiredChanging(value);
					this.SendPropertyChanging();
					this._writingEnglishOrFrenchRequired = value;
					this.SendPropertyChanged("writingEnglishOrFrenchRequired");
					this.OnwritingEnglishOrFrenchRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_writingEnglishAndFrenchRequired", DbType="Bit")]
		public System.Nullable<bool> writingEnglishAndFrenchRequired
		{
			get
			{
				return this._writingEnglishAndFrenchRequired;
			}
			set
			{
				if ((this._writingEnglishAndFrenchRequired != value))
				{
					this.OnwritingEnglishAndFrenchRequiredChanging(value);
					this.SendPropertyChanging();
					this._writingEnglishAndFrenchRequired = value;
					this.SendPropertyChanged("writingEnglishAndFrenchRequired");
					this.OnwritingEnglishAndFrenchRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherLanguageRequired", DbType="Bit")]
		public System.Nullable<bool> otherLanguageRequired
		{
			get
			{
				return this._otherLanguageRequired;
			}
			set
			{
				if ((this._otherLanguageRequired != value))
				{
					this.OnotherLanguageRequiredChanging(value);
					this.SendPropertyChanging();
					this._otherLanguageRequired = value;
					this.SendPropertyChanged("otherLanguageRequired");
					this.OnotherLanguageRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherLanguageExplanation", DbType="VarChar(150)")]
		public string otherLanguageExplanation
		{
			get
			{
				return this._otherLanguageExplanation;
			}
			set
			{
				if ((this._otherLanguageExplanation != value))
				{
					this.OnotherLanguageExplanationChanging(value);
					this.SendPropertyChanging();
					this._otherLanguageExplanation = value;
					this.SendPropertyChanged("otherLanguageExplanation");
					this.OnotherLanguageExplanationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vacationDays", DbType="Int")]
		public System.Nullable<int> vacationDays
		{
			get
			{
				return this._vacationDays;
			}
			set
			{
				if ((this._vacationDays != value))
				{
					this.OnvacationDaysChanging(value);
					this.SendPropertyChanging();
					this._vacationDays = value;
					this.SendPropertyChanged("vacationDays");
					this.OnvacationDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remuneration", DbType="Int")]
		public System.Nullable<int> remuneration
		{
			get
			{
				return this._remuneration;
			}
			set
			{
				if ((this._remuneration != value))
				{
					this.OnremunerationChanging(value);
					this.SendPropertyChanging();
					this._remuneration = value;
					this.SendPropertyChanged("remuneration");
					this.OnremunerationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherBenefit", DbType="VarChar(100)")]
		public string otherBenefit
		{
			get
			{
				return this._otherBenefit;
			}
			set
			{
				if ((this._otherBenefit != value))
				{
					this.OnotherBenefitChanging(value);
					this.SendPropertyChanging();
					this._otherBenefit = value;
					this.SendPropertyChanged("otherBenefit");
					this.OnotherBenefitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSeasonal", DbType="Bit")]
		public System.Nullable<bool> isSeasonal
		{
			get
			{
				return this._isSeasonal;
			}
			set
			{
				if ((this._isSeasonal != value))
				{
					this.OnisSeasonalChanging(value);
					this.SendPropertyChanging();
					this._isSeasonal = value;
					this.SendPropertyChanged("isSeasonal");
					this.OnisSeasonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isFullyCoveredLMIA", DbType="Bit")]
		public System.Nullable<bool> isFullyCoveredLMIA
		{
			get
			{
				return this._isFullyCoveredLMIA;
			}
			set
			{
				if ((this._isFullyCoveredLMIA != value))
				{
					this.OnisFullyCoveredLMIAChanging(value);
					this.SendPropertyChanging();
					this._isFullyCoveredLMIA = value;
					this.SendPropertyChanged("isFullyCoveredLMIA");
					this.OnisFullyCoveredLMIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notFullyCoveredReason", DbType="VarChar(150)")]
		public string notFullyCoveredReason
		{
			get
			{
				return this._notFullyCoveredReason;
			}
			set
			{
				if ((this._notFullyCoveredReason != value))
				{
					this.OnnotFullyCoveredReasonChanging(value);
					this.SendPropertyChanging();
					this._notFullyCoveredReason = value;
					this.SendPropertyChanged("notFullyCoveredReason");
					this.OnnotFullyCoveredReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isJobLicensed", DbType="Bit")]
		public System.Nullable<bool> isJobLicensed
		{
			get
			{
				return this._isJobLicensed;
			}
			set
			{
				if ((this._isJobLicensed != value))
				{
					this.OnisJobLicensedChanging(value);
					this.SendPropertyChanging();
					this._isJobLicensed = value;
					this.SendPropertyChanged("isJobLicensed");
					this.OnisJobLicensedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licenseAuthority", DbType="VarChar(150)")]
		public string licenseAuthority
		{
			get
			{
				return this._licenseAuthority;
			}
			set
			{
				if ((this._licenseAuthority != value))
				{
					this.OnlicenseAuthorityChanging(value);
					this.SendPropertyChanging();
					this._licenseAuthority = value;
					this.SendPropertyChanged("licenseAuthority");
					this.OnlicenseAuthorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licenseReady", DbType="Bit")]
		public System.Nullable<bool> licenseReady
		{
			get
			{
				return this._licenseReady;
			}
			set
			{
				if ((this._licenseReady != value))
				{
					this.OnlicenseReadyChanging(value);
					this.SendPropertyChanging();
					this._licenseReady = value;
					this.SendPropertyChanged("licenseReady");
					this.OnlicenseReadyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licenseReadyTime", DbType="Int")]
		public System.Nullable<int> licenseReadyTime
		{
			get
			{
				return this._licenseReadyTime;
			}
			set
			{
				if ((this._licenseReadyTime != value))
				{
					this.OnlicenseReadyTimeChanging(value);
					this.SendPropertyChanging();
					this._licenseReadyTime = value;
					this.SendPropertyChanged("licenseReadyTime");
					this.OnlicenseReadyTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licenseReadyUnit", DbType="VarChar(30)")]
		public string licenseReadyUnit
		{
			get
			{
				return this._licenseReadyUnit;
			}
			set
			{
				if ((this._licenseReadyUnit != value))
				{
					this.OnlicenseReadyUnitChanging(value);
					this.SendPropertyChanging();
					this._licenseReadyUnit = value;
					this.SendPropertyChanged("licenseReadyUnit");
					this.OnlicenseReadyUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isJobUnion", DbType="Bit")]
		public System.Nullable<bool> isJobUnion
		{
			get
			{
				return this._isJobUnion;
			}
			set
			{
				if ((this._isJobUnion != value))
				{
					this.OnisJobUnionChanging(value);
					this.SendPropertyChanging();
					this._isJobUnion = value;
					this.SendPropertyChanged("isJobUnion");
					this.OnisJobUnionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unionNameLocation", DbType="VarChar(150)")]
		public string unionNameLocation
		{
			get
			{
				return this._unionNameLocation;
			}
			set
			{
				if ((this._unionNameLocation != value))
				{
					this.OnunionNameLocationChanging(value);
					this.SendPropertyChanging();
					this._unionNameLocation = value;
					this.SendPropertyChanged("unionNameLocation");
					this.OnunionNameLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isUnionConsulted", DbType="Bit")]
		public System.Nullable<bool> isUnionConsulted
		{
			get
			{
				return this._isUnionConsulted;
			}
			set
			{
				if ((this._isUnionConsulted != value))
				{
					this.OnisUnionConsultedChanging(value);
					this.SendPropertyChanging();
					this._isUnionConsulted = value;
					this.SendPropertyChanged("isUnionConsulted");
					this.OnisUnionConsultedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unionNotExplanation", DbType="VarChar(150)")]
		public string unionNotExplanation
		{
			get
			{
				return this._unionNotExplanation;
			}
			set
			{
				if ((this._unionNotExplanation != value))
				{
					this.OnunionNotExplanationChanging(value);
					this.SendPropertyChanging();
					this._unionNotExplanation = value;
					this.SendPropertyChanged("unionNotExplanation");
					this.OnunionNotExplanationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unionOpinion", DbType="VarChar(150)")]
		public string unionOpinion
		{
			get
			{
				return this._unionOpinion;
			}
			set
			{
				if ((this._unionOpinion != value))
				{
					this.OnunionOpinionChanging(value);
					this.SendPropertyChanging();
					this._unionOpinion = value;
					this.SendPropertyChanged("unionOpinion");
					this.OnunionOpinionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attemptedRecruitCanadian", DbType="Bit")]
		public System.Nullable<bool> attemptedRecruitCanadian
		{
			get
			{
				return this._attemptedRecruitCanadian;
			}
			set
			{
				if ((this._attemptedRecruitCanadian != value))
				{
					this.OnattemptedRecruitCanadianChanging(value);
					this.SendPropertyChanging();
					this._attemptedRecruitCanadian = value;
					this.SendPropertyChanged("attemptedRecruitCanadian");
					this.OnattemptedRecruitCanadianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notAttemptedReason", DbType="VarChar(150)")]
		public string notAttemptedReason
		{
			get
			{
				return this._notAttemptedReason;
			}
			set
			{
				if ((this._notAttemptedReason != value))
				{
					this.OnnotAttemptedReasonChanging(value);
					this.SendPropertyChanging();
					this._notAttemptedReason = value;
					this.SendPropertyChanged("notAttemptedReason");
					this.OnnotAttemptedReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficialAdNumber", DbType="VarChar(20)")]
		public string OfficialAdNumber
		{
			get
			{
				return this._OfficialAdNumber;
			}
			set
			{
				if ((this._OfficialAdNumber != value))
				{
					this.OnOfficialAdNumberChanging(value);
					this.SendPropertyChanging();
					this._OfficialAdNumber = value;
					this.SendPropertyChanged("OfficialAdNumber");
					this.OnOfficialAdNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_briefBenefit", DbType="VarChar(150)")]
		public string briefBenefit
		{
			get
			{
				return this._briefBenefit;
			}
			set
			{
				if ((this._briefBenefit != value))
				{
					this.OnbriefBenefitChanging(value);
					this.SendPropertyChanging();
					this._briefBenefit = value;
					this.SendPropertyChanged("briefBenefit");
					this.OnbriefBenefitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detailedBenefit", DbType="VarChar(4000)")]
		public string detailedBenefit
		{
			get
			{
				return this._detailedBenefit;
			}
			set
			{
				if ((this._detailedBenefit != value))
				{
					this.OndetailedBenefitChanging(value);
					this.SendPropertyChanging();
					this._detailedBenefit = value;
					this.SendPropertyChanged("detailedBenefit");
					this.OndetailedBenefitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_briefRationaleOfferingJob", DbType="VarChar(150)")]
		public string briefRationaleOfferingJob
		{
			get
			{
				return this._briefRationaleOfferingJob;
			}
			set
			{
				if ((this._briefRationaleOfferingJob != value))
				{
					this.OnbriefRationaleOfferingJobChanging(value);
					this.SendPropertyChanging();
					this._briefRationaleOfferingJob = value;
					this.SendPropertyChanged("briefRationaleOfferingJob");
					this.OnbriefRationaleOfferingJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detailedRationaleOfferingJob", DbType="VarChar(4000)")]
		public string detailedRationaleOfferingJob
		{
			get
			{
				return this._detailedRationaleOfferingJob;
			}
			set
			{
				if ((this._detailedRationaleOfferingJob != value))
				{
					this.OndetailedRationaleOfferingJobChanging(value);
					this.SendPropertyChanging();
					this._detailedRationaleOfferingJob = value;
					this.SendPropertyChanged("detailedRationaleOfferingJob");
					this.OndetailedRationaleOfferingJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trainCanadian", DbType="Bit")]
		public System.Nullable<bool> trainCanadian
		{
			get
			{
				return this._trainCanadian;
			}
			set
			{
				if ((this._trainCanadian != value))
				{
					this.OntrainCanadianChanging(value);
					this.SendPropertyChanging();
					this._trainCanadian = value;
					this.SendPropertyChanged("trainCanadian");
					this.OntrainCanadianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noTrainReason", DbType="VarChar(150)")]
		public string noTrainReason
		{
			get
			{
				return this._noTrainReason;
			}
			set
			{
				if ((this._noTrainReason != value))
				{
					this.OnnoTrainReasonChanging(value);
					this.SendPropertyChanging();
					this._noTrainReason = value;
					this.SendPropertyChanged("noTrainReason");
					this.OnnoTrainReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trainPlanBrief", DbType="VarChar(150)")]
		public string trainPlanBrief
		{
			get
			{
				return this._trainPlanBrief;
			}
			set
			{
				if ((this._trainPlanBrief != value))
				{
					this.OntrainPlanBriefChanging(value);
					this.SendPropertyChanging();
					this._trainPlanBrief = value;
					this.SendPropertyChanged("trainPlanBrief");
					this.OntrainPlanBriefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trainPlanDetails", DbType="VarChar(4000)")]
		public string trainPlanDetails
		{
			get
			{
				return this._trainPlanDetails;
			}
			set
			{
				if ((this._trainPlanDetails != value))
				{
					this.OntrainPlanDetailsChanging(value);
					this.SendPropertyChanging();
					this._trainPlanDetails = value;
					this.SendPropertyChanged("trainPlanDetails");
					this.OntrainPlanDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_willProvideAccomadation", DbType="Bit")]
		public System.Nullable<bool> willProvideAccomadation
		{
			get
			{
				return this._willProvideAccomadation;
			}
			set
			{
				if ((this._willProvideAccomadation != value))
				{
					this.OnwillProvideAccomadationChanging(value);
					this.SendPropertyChanging();
					this._willProvideAccomadation = value;
					this.SendPropertyChanged("willProvideAccomadation");
					this.OnwillProvideAccomadationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notProvideButOffer", DbType="VarChar(150)")]
		public string notProvideButOffer
		{
			get
			{
				return this._notProvideButOffer;
			}
			set
			{
				if ((this._notProvideButOffer != value))
				{
					this.OnnotProvideButOfferChanging(value);
					this.SendPropertyChanging();
					this._notProvideButOffer = value;
					this.SendPropertyChanged("notProvideButOffer");
					this.OnnotProvideButOfferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provideRent", DbType="Int")]
		public System.Nullable<int> provideRent
		{
			get
			{
				return this._provideRent;
			}
			set
			{
				if ((this._provideRent != value))
				{
					this.OnprovideRentChanging(value);
					this.SendPropertyChanging();
					this._provideRent = value;
					this.SendPropertyChanged("provideRent");
					this.OnprovideRentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provideUnit", DbType="VarChar(30)")]
		public string provideUnit
		{
			get
			{
				return this._provideUnit;
			}
			set
			{
				if ((this._provideUnit != value))
				{
					this.OnprovideUnitChanging(value);
					this.SendPropertyChanging();
					this._provideUnit = value;
					this.SendPropertyChanged("provideUnit");
					this.OnprovideUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accommodationDescription", DbType="VarChar(150)")]
		public string accommodationDescription
		{
			get
			{
				return this._accommodationDescription;
			}
			set
			{
				if ((this._accommodationDescription != value))
				{
					this.OnaccommodationDescriptionChanging(value);
					this.SendPropertyChanging();
					this._accommodationDescription = value;
					this.SendPropertyChanged("accommodationDescription");
					this.OnaccommodationDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accomadationNotApplicalbe", DbType="Bit")]
		public System.Nullable<bool> accomadationNotApplicalbe
		{
			get
			{
				return this._accomadationNotApplicalbe;
			}
			set
			{
				if ((this._accomadationNotApplicalbe != value))
				{
					this.OnaccomadationNotApplicalbeChanging(value);
					this.SendPropertyChanging();
					this._accomadationNotApplicalbe = value;
					this.SendPropertyChanged("accomadationNotApplicalbe");
					this.OnaccomadationNotApplicalbeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whoIsFillingBrief", DbType="VarChar(150)")]
		public string whoIsFillingBrief
		{
			get
			{
				return this._whoIsFillingBrief;
			}
			set
			{
				if ((this._whoIsFillingBrief != value))
				{
					this.OnwhoIsFillingBriefChanging(value);
					this.SendPropertyChanging();
					this._whoIsFillingBrief = value;
					this.SendPropertyChanged("whoIsFillingBrief");
					this.OnwhoIsFillingBriefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whoIsFillingDetail", DbType="VarChar(4000)")]
		public string whoIsFillingDetail
		{
			get
			{
				return this._whoIsFillingDetail;
			}
			set
			{
				if ((this._whoIsFillingDetail != value))
				{
					this.OnwhoIsFillingDetailChanging(value);
					this.SendPropertyChanging();
					this._whoIsFillingDetail = value;
					this.SendPropertyChanged("whoIsFillingDetail");
					this.OnwhoIsFillingDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_howDidYouFindBrief", DbType="VarChar(150)")]
		public string howDidYouFindBrief
		{
			get
			{
				return this._howDidYouFindBrief;
			}
			set
			{
				if ((this._howDidYouFindBrief != value))
				{
					this.OnhowDidYouFindBriefChanging(value);
					this.SendPropertyChanging();
					this._howDidYouFindBrief = value;
					this.SendPropertyChanged("howDidYouFindBrief");
					this.OnhowDidYouFindBriefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_howDidYouFindDetail", DbType="VarChar(4000)")]
		public string howDidYouFindDetail
		{
			get
			{
				return this._howDidYouFindDetail;
			}
			set
			{
				if ((this._howDidYouFindDetail != value))
				{
					this.OnhowDidYouFindDetailChanging(value);
					this.SendPropertyChanging();
					this._howDidYouFindDetail = value;
					this.SendPropertyChanged("howDidYouFindDetail");
					this.OnhowDidYouFindDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_howDidYouDetermineBrief", DbType="VarChar(150)")]
		public string howDidYouDetermineBrief
		{
			get
			{
				return this._howDidYouDetermineBrief;
			}
			set
			{
				if ((this._howDidYouDetermineBrief != value))
				{
					this.OnhowDidYouDetermineBriefChanging(value);
					this.SendPropertyChanging();
					this._howDidYouDetermineBrief = value;
					this.SendPropertyChanged("howDidYouDetermineBrief");
					this.OnhowDidYouDetermineBriefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_howDidYouDetermineDetail", DbType="VarChar(4000)")]
		public string howDidYouDetermineDetail
		{
			get
			{
				return this._howDidYouDetermineDetail;
			}
			set
			{
				if ((this._howDidYouDetermineDetail != value))
				{
					this.OnhowDidYouDetermineDetailChanging(value);
					this.SendPropertyChanging();
					this._howDidYouDetermineDetail = value;
					this.SendPropertyChanged("howDidYouDetermineDetail");
					this.OnhowDidYouDetermineDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_howAndWhenOfferBrief", DbType="VarChar(150)")]
		public string howAndWhenOfferBrief
		{
			get
			{
				return this._howAndWhenOfferBrief;
			}
			set
			{
				if ((this._howAndWhenOfferBrief != value))
				{
					this.OnhowAndWhenOfferBriefChanging(value);
					this.SendPropertyChanging();
					this._howAndWhenOfferBrief = value;
					this.SendPropertyChanged("howAndWhenOfferBrief");
					this.OnhowAndWhenOfferBriefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_howAndWhenOfferDetail", DbType="VarChar(4000)")]
		public string howAndWhenOfferDetail
		{
			get
			{
				return this._howAndWhenOfferDetail;
			}
			set
			{
				if ((this._howAndWhenOfferDetail != value))
				{
					this.OnhowAndWhenOfferDetailChanging(value);
					this.SendPropertyChanging();
					this._howAndWhenOfferDetail = value;
					this.SendPropertyChanged("howAndWhenOfferDetail");
					this.OnhowAndWhenOfferDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLMIAApplication")]
	public partial class tblLMIAApplication : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _ProgramType;
		
		private System.Nullable<int> _StreamType;
		
		private System.Nullable<int> _EmployerId;
		
		private System.Nullable<int> _EmployeeId;
		
		private System.Nullable<int> _RCICId;
		
		private System.Nullable<int> _WorkLocationId;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _SubmittedDate;
		
		private System.Nullable<System.DateTime> _ClosedDate;
		
		private string _ApplicationNumber;
		
		private System.Nullable<decimal> _ApplicationFee;
		
		private string _SecondEmployer;
		
		private System.Nullable<int> _NumberofPosition;
		
		private System.Nullable<decimal> _ApplicationFeePerPosition;
		
		private System.Nullable<int> _PayMethod;
		
		private System.Nullable<bool> _MoreThanOneEmployer;
		
		private string _AnotherEmployerName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProgramTypeChanging(System.Nullable<int> value);
    partial void OnProgramTypeChanged();
    partial void OnStreamTypeChanging(System.Nullable<int> value);
    partial void OnStreamTypeChanged();
    partial void OnEmployerIdChanging(System.Nullable<int> value);
    partial void OnEmployerIdChanged();
    partial void OnEmployeeIdChanging(System.Nullable<int> value);
    partial void OnEmployeeIdChanged();
    partial void OnRCICIdChanging(System.Nullable<int> value);
    partial void OnRCICIdChanged();
    partial void OnWorkLocationIdChanging(System.Nullable<int> value);
    partial void OnWorkLocationIdChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnSubmittedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSubmittedDateChanged();
    partial void OnClosedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnClosedDateChanged();
    partial void OnApplicationNumberChanging(string value);
    partial void OnApplicationNumberChanged();
    partial void OnApplicationFeeChanging(System.Nullable<decimal> value);
    partial void OnApplicationFeeChanged();
    partial void OnSecondEmployerChanging(string value);
    partial void OnSecondEmployerChanged();
    partial void OnNumberofPositionChanging(System.Nullable<int> value);
    partial void OnNumberofPositionChanged();
    partial void OnApplicationFeePerPositionChanging(System.Nullable<decimal> value);
    partial void OnApplicationFeePerPositionChanged();
    partial void OnPayMethodChanging(System.Nullable<int> value);
    partial void OnPayMethodChanged();
    partial void OnMoreThanOneEmployerChanging(System.Nullable<bool> value);
    partial void OnMoreThanOneEmployerChanged();
    partial void OnAnotherEmployerNameChanging(string value);
    partial void OnAnotherEmployerNameChanged();
    #endregion
		
		public tblLMIAApplication()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramType", DbType="Int")]
		public System.Nullable<int> ProgramType
		{
			get
			{
				return this._ProgramType;
			}
			set
			{
				if ((this._ProgramType != value))
				{
					this.OnProgramTypeChanging(value);
					this.SendPropertyChanging();
					this._ProgramType = value;
					this.SendPropertyChanged("ProgramType");
					this.OnProgramTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreamType", DbType="Int")]
		public System.Nullable<int> StreamType
		{
			get
			{
				return this._StreamType;
			}
			set
			{
				if ((this._StreamType != value))
				{
					this.OnStreamTypeChanging(value);
					this.SendPropertyChanging();
					this._StreamType = value;
					this.SendPropertyChanged("StreamType");
					this.OnStreamTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployerId", DbType="Int")]
		public System.Nullable<int> EmployerId
		{
			get
			{
				return this._EmployerId;
			}
			set
			{
				if ((this._EmployerId != value))
				{
					this.OnEmployerIdChanging(value);
					this.SendPropertyChanging();
					this._EmployerId = value;
					this.SendPropertyChanged("EmployerId");
					this.OnEmployerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int")]
		public System.Nullable<int> EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RCICId", DbType="Int")]
		public System.Nullable<int> RCICId
		{
			get
			{
				return this._RCICId;
			}
			set
			{
				if ((this._RCICId != value))
				{
					this.OnRCICIdChanging(value);
					this.SendPropertyChanging();
					this._RCICId = value;
					this.SendPropertyChanged("RCICId");
					this.OnRCICIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkLocationId", DbType="Int")]
		public System.Nullable<int> WorkLocationId
		{
			get
			{
				return this._WorkLocationId;
			}
			set
			{
				if ((this._WorkLocationId != value))
				{
					this.OnWorkLocationIdChanging(value);
					this.SendPropertyChanging();
					this._WorkLocationId = value;
					this.SendPropertyChanged("WorkLocationId");
					this.OnWorkLocationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedDate", DbType="Date")]
		public System.Nullable<System.DateTime> SubmittedDate
		{
			get
			{
				return this._SubmittedDate;
			}
			set
			{
				if ((this._SubmittedDate != value))
				{
					this.OnSubmittedDateChanging(value);
					this.SendPropertyChanging();
					this._SubmittedDate = value;
					this.SendPropertyChanged("SubmittedDate");
					this.OnSubmittedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosedDate", DbType="Date")]
		public System.Nullable<System.DateTime> ClosedDate
		{
			get
			{
				return this._ClosedDate;
			}
			set
			{
				if ((this._ClosedDate != value))
				{
					this.OnClosedDateChanging(value);
					this.SendPropertyChanging();
					this._ClosedDate = value;
					this.SendPropertyChanged("ClosedDate");
					this.OnClosedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationNumber", DbType="VarChar(20)")]
		public string ApplicationNumber
		{
			get
			{
				return this._ApplicationNumber;
			}
			set
			{
				if ((this._ApplicationNumber != value))
				{
					this.OnApplicationNumberChanging(value);
					this.SendPropertyChanging();
					this._ApplicationNumber = value;
					this.SendPropertyChanged("ApplicationNumber");
					this.OnApplicationNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationFee", DbType="Money")]
		public System.Nullable<decimal> ApplicationFee
		{
			get
			{
				return this._ApplicationFee;
			}
			set
			{
				if ((this._ApplicationFee != value))
				{
					this.OnApplicationFeeChanging(value);
					this.SendPropertyChanging();
					this._ApplicationFee = value;
					this.SendPropertyChanged("ApplicationFee");
					this.OnApplicationFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondEmployer", DbType="VarChar(30)")]
		public string SecondEmployer
		{
			get
			{
				return this._SecondEmployer;
			}
			set
			{
				if ((this._SecondEmployer != value))
				{
					this.OnSecondEmployerChanging(value);
					this.SendPropertyChanging();
					this._SecondEmployer = value;
					this.SendPropertyChanged("SecondEmployer");
					this.OnSecondEmployerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberofPosition", DbType="Int")]
		public System.Nullable<int> NumberofPosition
		{
			get
			{
				return this._NumberofPosition;
			}
			set
			{
				if ((this._NumberofPosition != value))
				{
					this.OnNumberofPositionChanging(value);
					this.SendPropertyChanging();
					this._NumberofPosition = value;
					this.SendPropertyChanged("NumberofPosition");
					this.OnNumberofPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationFeePerPosition", DbType="Money")]
		public System.Nullable<decimal> ApplicationFeePerPosition
		{
			get
			{
				return this._ApplicationFeePerPosition;
			}
			set
			{
				if ((this._ApplicationFeePerPosition != value))
				{
					this.OnApplicationFeePerPositionChanging(value);
					this.SendPropertyChanging();
					this._ApplicationFeePerPosition = value;
					this.SendPropertyChanged("ApplicationFeePerPosition");
					this.OnApplicationFeePerPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayMethod", DbType="Int")]
		public System.Nullable<int> PayMethod
		{
			get
			{
				return this._PayMethod;
			}
			set
			{
				if ((this._PayMethod != value))
				{
					this.OnPayMethodChanging(value);
					this.SendPropertyChanging();
					this._PayMethod = value;
					this.SendPropertyChanged("PayMethod");
					this.OnPayMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoreThanOneEmployer", DbType="Bit")]
		public System.Nullable<bool> MoreThanOneEmployer
		{
			get
			{
				return this._MoreThanOneEmployer;
			}
			set
			{
				if ((this._MoreThanOneEmployer != value))
				{
					this.OnMoreThanOneEmployerChanging(value);
					this.SendPropertyChanging();
					this._MoreThanOneEmployer = value;
					this.SendPropertyChanged("MoreThanOneEmployer");
					this.OnMoreThanOneEmployerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnotherEmployerName", DbType="VarChar(150)")]
		public string AnotherEmployerName
		{
			get
			{
				return this._AnotherEmployerName;
			}
			set
			{
				if ((this._AnotherEmployerName != value))
				{
					this.OnAnotherEmployerNameChanging(value);
					this.SendPropertyChanging();
					this._AnotherEmployerName = value;
					this.SendPropertyChanged("AnotherEmployerName");
					this.OnAnotherEmployerNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
